/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jaeyeon Nam (https://sketchfab.com/jaeysart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/squid-game-pinksoldier-8f6112f88ea743e8a468ac017bb2c0e2
Title: Squid Game : PinkSoldier
*/

import React, { useEffect, useRef } from "react";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";

export function Squid(props) {
  const group = useRef();
  
  const { animations: typingAnimations } = useFBX("src/assets/animations/Typing.fbx");
  const { actions } = useAnimations(typingAnimations, group);
  typingAnimations[0].name = "Typing";
  console.log(typingAnimations);

  useEffect(() => {
    actions["Typing"].reset().play();
  }, [actions]);

  const { nodes, materials } = useGLTF("src/assets/3d/squid.glb");
  return (
    <group {...props} ref={group} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("src/assets/3d/squid.glb");
